services:
  - type: web
    name: eda-backend-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn run:app
    healthCheckPath: /api/health
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: SECRET_KEY
        generateValue: true
